// AUTO-GENERATED by scripts/build-ar-assets.mjs (v3). DO NOT hand-edit.
// Web-AR manifest: true-size framed-print models for phone AR.
//   • GLB "frame shells" (model-viewer / WebXR / Android) — swap the "Artwork"
//     material baseColorTexture at runtime to the chosen colourway.
//   • USDZ matrix (iOS Quick Look) — one pre-baked file per
//     colourway-image × size × frame, authored at the size's TRUE metres.
// Regenerate with: node scripts/build-ar-assets.mjs

export interface ArSize {
  id: "a3" | "a2" | "a1" | "a0";
  label: string;
  cm: number;
  metres: number;
  tierId: string;
  anchor?: boolean;
}

export interface ArFrame {
  id: "black-oak" | "natural-oak";
  label: string;
  swatch: string;
}

export const AR_SIZES: ArSize[] = [
  { id: "a3", label: "A3", cm: 29.5, metres: 0.295, tierId: "atelier" },
  { id: "a2", label: "A2", cm: 42, metres: 0.42, tierId: "collector", anchor: true },
  { id: "a1", label: "A1", cm: 59.5, metres: 0.595, tierId: "atelier-grande" },
  { id: "a0", label: "A0", cm: 84, metres: 0.84, tierId: "heirloom" },
];

export const AR_FRAMES: ArFrame[] = [
  { id: "black-oak", label: "Black-stained oak", swatch: "#1c1a17" },
  { id: "natural-oak", label: "Natural oak", swatch: "#b8966a" },
];

export const AR_DEFAULT_FRAME: ArFrame["id"] = "black-oak";
export const AR_DEFAULT_SIZE: ArSize["id"] = "a2";

/** The GLB frame-shell asset path per frame finish (texture swapped at runtime). */
export const AR_FRAME_GLB: Record<ArFrame["id"], string> = {
  "black-oak": "/ar/frame-black-oak-v3.glb",
  "natural-oak": "/ar/frame-natural-oak-v3.glb",
};

/** The metres the GLB shells are authored at (A2 anchor). Scale at runtime to
 *  the selected size = AR_SIZES[sizeId].metres / AR_GLB_BASE_METRES. */
export const AR_GLB_BASE_METRES = 0.42;

/** Slug a colourway image path → its AR filename stem (mirror of the builder). */
export const arSlug = (image: string): string =>
  image
    .replace("/img/paintings/", "")
    .replace(/\.(jpg|jpeg|png|webp)$/i, "")
    .toLowerCase();

/** The set of generated USDZ keys: `<paintingId>__<imageSlug>__<sizeId>__<frame>`. */
const AR_USDZ_KEYS: ReadonlySet<string> = new Set([
  "english-bluebells__english-bluebells-v3__a0__black-oak",
  "english-bluebells__english-bluebells-v3__a0__natural-oak",
  "english-bluebells__english-bluebells-v3__a1__black-oak",
  "english-bluebells__english-bluebells-v3__a1__natural-oak",
  "english-bluebells__english-bluebells-v3__a2__black-oak",
  "english-bluebells__english-bluebells-v3__a2__natural-oak",
  "english-bluebells__english-bluebells-v3__a3__black-oak",
  "english-bluebells__english-bluebells-v3__a3__natural-oak",
  "enneagon-swans__enneagon-antique-pink__a0__black-oak",
  "enneagon-swans__enneagon-antique-pink__a0__natural-oak",
  "enneagon-swans__enneagon-antique-pink__a1__black-oak",
  "enneagon-swans__enneagon-antique-pink__a1__natural-oak",
  "enneagon-swans__enneagon-antique-pink__a2__black-oak",
  "enneagon-swans__enneagon-antique-pink__a2__natural-oak",
  "enneagon-swans__enneagon-antique-pink__a3__black-oak",
  "enneagon-swans__enneagon-antique-pink__a3__natural-oak",
  "enneagon-swans__enneagon-cygnus-gold__a0__black-oak",
  "enneagon-swans__enneagon-cygnus-gold__a0__natural-oak",
  "enneagon-swans__enneagon-cygnus-gold__a1__black-oak",
  "enneagon-swans__enneagon-cygnus-gold__a1__natural-oak",
  "enneagon-swans__enneagon-cygnus-gold__a2__black-oak",
  "enneagon-swans__enneagon-cygnus-gold__a2__natural-oak",
  "enneagon-swans__enneagon-cygnus-gold__a3__black-oak",
  "enneagon-swans__enneagon-cygnus-gold__a3__natural-oak",
  "enneagon-swans__enneagon-glacier-blue__a0__black-oak",
  "enneagon-swans__enneagon-glacier-blue__a0__natural-oak",
  "enneagon-swans__enneagon-glacier-blue__a1__black-oak",
  "enneagon-swans__enneagon-glacier-blue__a1__natural-oak",
  "enneagon-swans__enneagon-glacier-blue__a2__black-oak",
  "enneagon-swans__enneagon-glacier-blue__a2__natural-oak",
  "enneagon-swans__enneagon-glacier-blue__a3__black-oak",
  "enneagon-swans__enneagon-glacier-blue__a3__natural-oak",
  "enneagon-swans__enneagon-solstice-orange__a0__black-oak",
  "enneagon-swans__enneagon-solstice-orange__a0__natural-oak",
  "enneagon-swans__enneagon-solstice-orange__a1__black-oak",
  "enneagon-swans__enneagon-solstice-orange__a1__natural-oak",
  "enneagon-swans__enneagon-solstice-orange__a2__black-oak",
  "enneagon-swans__enneagon-solstice-orange__a2__natural-oak",
  "enneagon-swans__enneagon-solstice-orange__a3__black-oak",
  "enneagon-swans__enneagon-solstice-orange__a3__natural-oak",
  "enneagon-swans__enneagon-velvet-purple__a0__black-oak",
  "enneagon-swans__enneagon-velvet-purple__a0__natural-oak",
  "enneagon-swans__enneagon-velvet-purple__a1__black-oak",
  "enneagon-swans__enneagon-velvet-purple__a1__natural-oak",
  "enneagon-swans__enneagon-velvet-purple__a2__black-oak",
  "enneagon-swans__enneagon-velvet-purple__a2__natural-oak",
  "enneagon-swans__enneagon-velvet-purple__a3__black-oak",
  "enneagon-swans__enneagon-velvet-purple__a3__natural-oak",
  "flower-of-life__fol-kaleidoscope__a0__black-oak",
  "flower-of-life__fol-kaleidoscope__a0__natural-oak",
  "flower-of-life__fol-kaleidoscope__a1__black-oak",
  "flower-of-life__fol-kaleidoscope__a1__natural-oak",
  "flower-of-life__fol-kaleidoscope__a2__black-oak",
  "flower-of-life__fol-kaleidoscope__a2__natural-oak",
  "flower-of-life__fol-kaleidoscope__a3__black-oak",
  "flower-of-life__fol-kaleidoscope__a3__natural-oak",
  "lulin__lulin-original__a0__black-oak",
  "lulin__lulin-original__a0__natural-oak",
  "lulin__lulin-original__a1__black-oak",
  "lulin__lulin-original__a1__natural-oak",
  "lulin__lulin-original__a2__black-oak",
  "lulin__lulin-original__a2__natural-oak",
  "lulin__lulin-original__a3__black-oak",
  "lulin__lulin-original__a3__natural-oak",
  "ophiuchus__ophiuchus-original__a0__black-oak",
  "ophiuchus__ophiuchus-original__a0__natural-oak",
  "ophiuchus__ophiuchus-original__a1__black-oak",
  "ophiuchus__ophiuchus-original__a1__natural-oak",
  "ophiuchus__ophiuchus-original__a2__black-oak",
  "ophiuchus__ophiuchus-original__a2__natural-oak",
  "ophiuchus__ophiuchus-original__a3__black-oak",
  "ophiuchus__ophiuchus-original__a3__natural-oak",
  "orchis-7__orchis7-aquamarine-blue__a0__black-oak",
  "orchis-7__orchis7-aquamarine-blue__a0__natural-oak",
  "orchis-7__orchis7-aquamarine-blue__a1__black-oak",
  "orchis-7__orchis7-aquamarine-blue__a1__natural-oak",
  "orchis-7__orchis7-aquamarine-blue__a2__black-oak",
  "orchis-7__orchis7-aquamarine-blue__a2__natural-oak",
  "orchis-7__orchis7-aquamarine-blue__a3__black-oak",
  "orchis-7__orchis7-aquamarine-blue__a3__natural-oak",
  "orchis-7__orchis7-rubedo-red__a0__black-oak",
  "orchis-7__orchis7-rubedo-red__a0__natural-oak",
  "orchis-7__orchis7-rubedo-red__a1__black-oak",
  "orchis-7__orchis7-rubedo-red__a1__natural-oak",
  "orchis-7__orchis7-rubedo-red__a2__black-oak",
  "orchis-7__orchis7-rubedo-red__a2__natural-oak",
  "orchis-7__orchis7-rubedo-red__a3__black-oak",
  "orchis-7__orchis7-rubedo-red__a3__natural-oak",
  "peacock-minerva__peacock-blood-moon-red__a0__black-oak",
  "peacock-minerva__peacock-blood-moon-red__a0__natural-oak",
  "peacock-minerva__peacock-blood-moon-red__a1__black-oak",
  "peacock-minerva__peacock-blood-moon-red__a1__natural-oak",
  "peacock-minerva__peacock-blood-moon-red__a2__black-oak",
  "peacock-minerva__peacock-blood-moon-red__a2__natural-oak",
  "peacock-minerva__peacock-blood-moon-red__a3__black-oak",
  "peacock-minerva__peacock-blood-moon-red__a3__natural-oak",
  "peacock-minerva__peacock-mary-pink__a0__black-oak",
  "peacock-minerva__peacock-mary-pink__a0__natural-oak",
  "peacock-minerva__peacock-mary-pink__a1__black-oak",
  "peacock-minerva__peacock-mary-pink__a1__natural-oak",
  "peacock-minerva__peacock-mary-pink__a2__black-oak",
  "peacock-minerva__peacock-mary-pink__a2__natural-oak",
  "peacock-minerva__peacock-mary-pink__a3__black-oak",
  "peacock-minerva__peacock-mary-pink__a3__natural-oak",
  "peacock-minerva__peacock-moroccan-purple__a0__black-oak",
  "peacock-minerva__peacock-moroccan-purple__a0__natural-oak",
  "peacock-minerva__peacock-moroccan-purple__a1__black-oak",
  "peacock-minerva__peacock-moroccan-purple__a1__natural-oak",
  "peacock-minerva__peacock-moroccan-purple__a2__black-oak",
  "peacock-minerva__peacock-moroccan-purple__a2__natural-oak",
  "peacock-minerva__peacock-moroccan-purple__a3__black-oak",
  "peacock-minerva__peacock-moroccan-purple__a3__natural-oak",
  "peacock-minerva__peacock-persian-indigo__a0__black-oak",
  "peacock-minerva__peacock-persian-indigo__a0__natural-oak",
  "peacock-minerva__peacock-persian-indigo__a1__black-oak",
  "peacock-minerva__peacock-persian-indigo__a1__natural-oak",
  "peacock-minerva__peacock-persian-indigo__a2__black-oak",
  "peacock-minerva__peacock-persian-indigo__a2__natural-oak",
  "peacock-minerva__peacock-persian-indigo__a3__black-oak",
  "peacock-minerva__peacock-persian-indigo__a3__natural-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a0__black-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a0__natural-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a1__black-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a1__natural-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a2__black-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a2__natural-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a3__black-oak",
  "peacock-minerva__peacock-sahara-sand-yellow__a3__natural-oak",
  "slipper-orchids__orchids30-garnet-red__a0__black-oak",
  "slipper-orchids__orchids30-garnet-red__a0__natural-oak",
  "slipper-orchids__orchids30-garnet-red__a1__black-oak",
  "slipper-orchids__orchids30-garnet-red__a1__natural-oak",
  "slipper-orchids__orchids30-garnet-red__a2__black-oak",
  "slipper-orchids__orchids30-garnet-red__a2__natural-oak",
  "slipper-orchids__orchids30-garnet-red__a3__black-oak",
  "slipper-orchids__orchids30-garnet-red__a3__natural-oak",
  "slipper-orchids__orchids30-lightning-blue__a0__black-oak",
  "slipper-orchids__orchids30-lightning-blue__a0__natural-oak",
  "slipper-orchids__orchids30-lightning-blue__a1__black-oak",
  "slipper-orchids__orchids30-lightning-blue__a1__natural-oak",
  "slipper-orchids__orchids30-lightning-blue__a2__black-oak",
  "slipper-orchids__orchids30-lightning-blue__a2__natural-oak",
  "slipper-orchids__orchids30-lightning-blue__a3__black-oak",
  "slipper-orchids__orchids30-lightning-blue__a3__natural-oak",
  "slipper-orchids__orchids30-manipura-yellow__a0__black-oak",
  "slipper-orchids__orchids30-manipura-yellow__a0__natural-oak",
  "slipper-orchids__orchids30-manipura-yellow__a1__black-oak",
  "slipper-orchids__orchids30-manipura-yellow__a1__natural-oak",
  "slipper-orchids__orchids30-manipura-yellow__a2__black-oak",
  "slipper-orchids__orchids30-manipura-yellow__a2__natural-oak",
  "slipper-orchids__orchids30-manipura-yellow__a3__black-oak",
  "slipper-orchids__orchids30-manipura-yellow__a3__natural-oak",
  "slipper-orchids__orchids30-nebula-purple__a0__black-oak",
  "slipper-orchids__orchids30-nebula-purple__a0__natural-oak",
  "slipper-orchids__orchids30-nebula-purple__a1__black-oak",
  "slipper-orchids__orchids30-nebula-purple__a1__natural-oak",
  "slipper-orchids__orchids30-nebula-purple__a2__black-oak",
  "slipper-orchids__orchids30-nebula-purple__a2__natural-oak",
  "slipper-orchids__orchids30-nebula-purple__a3__black-oak",
  "slipper-orchids__orchids30-nebula-purple__a3__natural-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a0__black-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a0__natural-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a1__black-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a1__natural-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a2__black-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a2__natural-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a3__black-oak",
  "tridecagon-moon-star__tridecagon-coral-reef__a3__natural-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a0__black-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a0__natural-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a1__black-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a1__natural-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a2__black-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a2__natural-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a3__black-oak",
  "tridecagon-moon-star__tridecagon-moonstone-blue__a3__natural-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a0__black-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a0__natural-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a1__black-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a1__natural-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a2__black-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a2__natural-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a3__black-oak",
  "tridecagon-moon-star__tridecagon-sage-green__a3__natural-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a0__black-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a0__natural-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a1__black-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a1__natural-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a2__black-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a2__natural-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a3__black-oak",
  "tridecagon-moon-star__tridecagon-supernova-violet__a3__natural-oak",
  "wild-rose__wild-rose-sussex-pink__a0__black-oak",
  "wild-rose__wild-rose-sussex-pink__a0__natural-oak",
  "wild-rose__wild-rose-sussex-pink__a1__black-oak",
  "wild-rose__wild-rose-sussex-pink__a1__natural-oak",
  "wild-rose__wild-rose-sussex-pink__a2__black-oak",
  "wild-rose__wild-rose-sussex-pink__a2__natural-oak",
  "wild-rose__wild-rose-sussex-pink__a3__black-oak",
  "wild-rose__wild-rose-sussex-pink__a3__natural-oak",
]);

/** Painting ids that have ANY AR asset (GLB shell + at least one USDZ). */
const AR_PAINTINGS: ReadonlySet<string> = new Set([
  "english-bluebells",
  "enneagon-swans",
  "flower-of-life",
  "lulin",
  "ophiuchus",
  "orchis-7",
  "peacock-minerva",
  "slipper-orchids",
  "tridecagon-moon-star",
  "wild-rose",
]);

/** The iOS Quick Look USDZ path for a (painting, colourway image, size, frame),
 *  or null if that exact asset was not generated. */
export const arUsdz = (
  paintingId: string,
  image: string,
  sizeId: ArSize["id"],
  frame: ArFrame["id"],
): string | null => {
  const slug = arSlug(image);
  const key = `${paintingId}__${slug}__${sizeId}__${frame}`;
  if (!AR_USDZ_KEYS.has(key)) return null;
  return `/ar/${paintingId}-${slug}-${sizeId}-${frame}-v3.usdz`;
};

/** Whether a painting has AR available at all. */
export const hasAr = (paintingId: string): boolean => AR_PAINTINGS.has(paintingId);
