// AUTO-GENERATED by scripts/colourway-tints.mjs — do not edit by hand.
// Per-colourway "Painted Wall" atmosphere tints: hue extracted from the
// artwork (chroma-weighted OKLCH median), lightness/chroma are HOUSE values
// (wall oklch(0.32 0.055 H), halo oklch(0.62 0.09 H)) so every page shares
// one material register while the hue follows the selected colourway.
// Re-run the script when a colourway image changes. OVERRIDES win.

export interface ColourwayTint {
  wall: string;
  halo: string;
}

const GENERATED: Record<string, ColourwayTint> = {
  "/img/paintings/wild-rose-sussex-pink.jpg": { wall: "#3c320d", halo: "#998542" }, // H 93
  "/img/paintings/english-bluebells-v3.jpg": { wall: "#1d344e", halo: "#5d89bb" }, // H 252
  "/img/paintings/orchis7-rubedo-red.jpg": { wall: "#4b2726", halo: "#b6706f" }, // H 21
  "/img/paintings/fol-kaleidoscope.jpg": { wall: "#2e2f4e", halo: "#7d7fbb" }, // H 282
  "/img/paintings/orchids30-nebula-purple.jpg": { wall: "#2e2f4e", halo: "#7d7fbb" }, // H 282
  "/img/paintings/orchids30-lightning-blue.jpg": { wall: "#2b304f", halo: "#7781bc" }, // H 276
  "/img/paintings/orchids30-garnet-red.jpg": { wall: "#4b2820", halo: "#b67263" }, // H 33
  "/img/paintings/orchids30-manipura-yellow.jpg": { wall: "#3a330e", halo: "#948743" }, // H 99
  "/img/paintings/peacock-persian-indigo.jpg": { wall: "#28314f", halo: "#7183bd" }, // H 270
  "/img/paintings/peacock-blood-moon-red.jpg": { wall: "#4b2725", halo: "#b6706c" }, // H 24
  "/img/paintings/peacock-sahara-sand-yellow.jpg": { wall: "#452d10", halo: "#a97c47" }, // H 69
  "/img/paintings/peacock-moroccan-purple.jpg": { wall: "#382c4a", halo: "#9179b3" }, // H 303
  "/img/paintings/peacock-mary-pink.jpg": { wall: "#482635", halo: "#b16f8a" }, // H 354
  "/img/paintings/ophiuchus-original.jpg": { wall: "#4b2722", halo: "#b67166" }, // H 30
  "/img/paintings/tridecagon-sage-green.jpg": { wall: "#28391a", halo: "#729258" }, // H 132
  "/img/paintings/tridecagon-moonstone-blue.jpg": { wall: "#482b16", halo: "#b07750" }, // H 55
  "/img/paintings/tridecagon-supernova-violet.jpg": { wall: "#2e2f4e", halo: "#7d7fbb" }, // H 282
  "/img/paintings/tridecagon-coral-reef.jpg": { wall: "#363510", halo: "#8b8a47" }, // H 108
  "/img/paintings/lulin-original.jpg": { wall: "#41300d", halo: "#a28043" }, // H 81
  "/img/paintings/enneagon-cygnus-gold.jpg": { wall: "#3a330e", halo: "#948743" }, // H 99
  "/img/paintings/enneagon-glacier-blue.jpg": { wall: "#412943", halo: "#a173a5" }, // H 324
  "/img/paintings/enneagon-solstice-orange.jpg": { wall: "#462d11", halo: "#ab7b49" }, // H 66
  "/img/paintings/enneagon-antique-pink.jpg": { wall: "#4a2630", halo: "#b46f81" }, // H 3
  "/img/paintings/enneagon-velvet-purple.jpg": { wall: "#3d2a46", halo: "#9b75ac" }, // H 315
};

/** Hand-fix a colourway here if the extracted hue ever reads wrong. */
const OVERRIDES: Record<string, ColourwayTint> = {
  // Moonstone Blue is a PALE cool canvas — every pixel sits under the chroma
  // gate, so extraction fell to the warm-umber fallback, which clashes hard
  // (eyeballed 2026-07-03). Hand-set to its true moonstone slate:
  // oklch(0.32 0.05 240) / oklch(0.62 0.08 240).
  "/img/paintings/tridecagon-moonstone-blue.jpg": { wall: "#18364a", halo: "#578db2" },
};

export const DEFAULT_TINT: ColourwayTint = { wall: "#2a241c", halo: "#8a7a63" };

export const COLOURWAY_TINTS: Record<string, ColourwayTint> = {
  ...GENERATED,
  ...OVERRIDES,
};
