// AUTO-GENERATED by scripts/build-wall-models.mjs — DO NOT hand-edit.
// The frameless wall-model manifest for the "See on Your Wall" AR feature.
// GLB shell is shared (runtime texture-swap + scale); USDZ is per size.
import type { ArtworkSizeId } from "./artworkSizes";

export const WALL_MODEL_VERSION = "v1";
export const WALL_SHELL_GLB = "/models/wall/canvas-frameless-v1.glb";

/** Slug a colourway image path → its wall-model asset stem. */
export const wallSlug = (image: string): string =>
  image.replace("/img/paintings/", "").replace(/\.(jpe?g|png|webp)$/i, "").toLowerCase();

/** Set of generated USDZ keys: `<paintingId>__<imageSlug>__<sizeId>`. */
const WALL_USDZ_KEYS: ReadonlySet<string> = new Set(["english-bluebells__english-bluebells-v3__a0","english-bluebells__english-bluebells-v3__a1","english-bluebells__english-bluebells-v3__a2","english-bluebells__english-bluebells-v3__a3","enneagon-swans__enneagon-cygnus-gold__a0","enneagon-swans__enneagon-cygnus-gold__a1","enneagon-swans__enneagon-cygnus-gold__a2","enneagon-swans__enneagon-cygnus-gold__a3","flower-of-life__fol-kaleidoscope__a0","flower-of-life__fol-kaleidoscope__a1","flower-of-life__fol-kaleidoscope__a2","flower-of-life__fol-kaleidoscope__a3","lulin__lulin-original__a0","lulin__lulin-original__a1","lulin__lulin-original__a2","lulin__lulin-original__a3","orchis-7__orchis7-rubedo-red__a0","orchis-7__orchis7-rubedo-red__a1","orchis-7__orchis7-rubedo-red__a2","orchis-7__orchis7-rubedo-red__a3","peacock-minerva__peacock-persian-indigo__a0","peacock-minerva__peacock-persian-indigo__a1","peacock-minerva__peacock-persian-indigo__a2","peacock-minerva__peacock-persian-indigo__a3","slipper-orchids__orchids30-nebula-purple__a0","slipper-orchids__orchids30-nebula-purple__a1","slipper-orchids__orchids30-nebula-purple__a2","slipper-orchids__orchids30-nebula-purple__a3","tridecagon-moon-star__tridecagon-sage-green__a0","tridecagon-moon-star__tridecagon-sage-green__a1","tridecagon-moon-star__tridecagon-sage-green__a2","tridecagon-moon-star__tridecagon-sage-green__a3","wild-rose__wild-rose-sussex-pink__a0","wild-rose__wild-rose-sussex-pink__a1","wild-rose__wild-rose-sussex-pink__a2","wild-rose__wild-rose-sussex-pink__a3"]);

/** Painting ids that have at least the shared GLB shell available (all do). */
const WALL_PAINTINGS: ReadonlySet<string> = new Set(["english-bluebells","enneagon-swans","flower-of-life","lulin","orchis-7","peacock-minerva","slipper-orchids","tridecagon-moon-star","wild-rose"]);

/** iOS Quick Look USDZ path for a (painting, colourway image, size), or null. */
export const wallUsdz = (
  paintingId: string,
  image: string,
  sizeId: ArtworkSizeId,
): string | null => {
  const key = `${paintingId}__${wallSlug(image)}__${sizeId}`;
  return WALL_USDZ_KEYS.has(key)
    ? `/models/wall/${paintingId}-${wallSlug(image)}-${sizeId}-v1.usdz`
    : null;
};

/** Whether a painting has wall-model coverage (the GLB shell always applies). */
export const hasWallModel = (paintingId: string): boolean => WALL_PAINTINGS.has(paintingId);
