import { type ReactNode } from "react";
import { asset } from "../lib/asset";

/**
 * FrameWrap + glazing sheen for the product hero. When a buyer ticks framing and
 * picks a moulding, the print shows INSIDE a PHOTOREAL frame; picking a glazing
 * changes the glass (glossy acrylic vs clean anti-reflective). All live per
 * selection (Hugo).
 *
 * ⚠️ SIZE INVARIANT (Hugo): the framed preview occupies the SAME footprint as the
 * unframed print — the moulding is the element's BORDER (box-sizing: border-box),
 * so the PRINT shrinks to make room and the outer size never changes.
 *
 * REALISM (2026-07-16, Hugo: the old flat CSS-gradient border "looks terrible and
 * like a cartoon"): the moulding is now a baked photoreal asset — a mitred 4-rail
 * frame with a real bevel profile (outer highlight → lit face → cove shadow →
 * inner lip → dark rebate line), fine longitudinal wood grain, and baked top-left
 * directional light — applied via `border-image` 9-slice so the corners mitre
 * correctly at any print aspect-ratio and the moulding keeps its detail at any
 * size. Assets are generated by scripts/frame-mouldings.sh into
 * /public/img/frames/<id>-frame-v1.png (immutable cache → bump to -vN on change).
 */

// Keyed to FRAME_STYLES ids in paintings.ts. Each is a 1200×1200 PNG with a
// transparent centre window, sliced at 170px.
// PHOTOREAL (v2, 2026-07-24): each source is Point 101's OWN moulding
// photography — their four real rail images per frame, mitred into a 9-slice
// border-image (scripts/frame-mouldings.sh's pipeline, real photo rails instead
// of colour recipes). So every product's frame preview matches Point 101
// exactly. Bump the -vN suffix on any re-bake (/img is immutable-cached).
const FRAME_ASSET: Record<string, string> = {
  "natural-oak": "/img/frames/natural-oak-frame-v2.webp",
  "stained-black": "/img/frames/stained-black-frame-v2.webp",
  white: "/img/frames/white-frame-v2.webp",
  "walnut-tray": "/img/frames/walnut-tray-frame-v2.webp",
  "black-lacquer": "/img/frames/black-lacquer-frame-v2.webp",
  "walnut-grain": "/img/frames/walnut-grain-frame-v2.webp",
  wenge: "/img/frames/wenge-frame-v2.webp",
  ash: "/img/frames/ash-frame-v2.webp",
  "white-stained": "/img/frames/white-stained-frame-v2.webp",
  silver: "/img/frames/silver-frame-v2.webp",
  gold: "/img/frames/gold-frame-v2.webp",
  "silver-aluminium": "/img/frames/silver-aluminium-frame-v2.webp",
  "black-aluminium": "/img/frames/black-aluminium-frame-v2.webp",
  "box-black": "/img/frames/box-black-frame-v2.webp",
  "box-oak": "/img/frames/box-oak-frame-v2.webp",
  "ayous-gold": "/img/frames/ayous-gold-frame-v2.webp",
  "ornate-gold": "/img/frames/ornate-gold-frame-v2.webp",
};
const FRAME_SLICE = 170; // px slice in the 1200px source (matches the script's M)

/* ── Glazing ────────────────────────────────────────────────────────────────
 * Art acrylic: a real, visible glass glare — a diagonal reflection band + a
 * top-left window highlight (mix-blend screen, like light bouncing off glass).
 * Anti-reflective (museum): near-invisible, NO streak — the whole point of the
 * upgrade — just the faintest even veil so it still reads as glazed. Showing the
 * two side by side makes the difference obvious (Hugo). */
export const GlazingOverlay = ({ glazing }: { glazing: string }) => {
  const acrylic = glazing !== "museum-glass"; // default (art-acrylic) is the glossy one
  return (
    <div
      className="pointer-events-none absolute inset-0"
      style={{
        mixBlendMode: "screen",
        background: acrylic
          ? // Clearly-visible gallery glass, but still natural: a bright specular
            // BLOOM in the top-left corner + a defined-yet-soft-edged diagonal
            // GLEAM band sweeping the upper-left, feathering fully to clear before
            // the lower-right — so the reflection reads unmistakably as glass while
            // the rest of the print stays crisp and legible (no washed-out haze).
            // A faint parallel second gleam sells the "sheet of glass" read.
            "radial-gradient(140% 105% at 9% 3%, rgba(255,255,255,0.34) 0%, rgba(255,255,255,0.10) 22%, rgba(255,255,255,0) 44%), " +
            "linear-gradient(121deg, rgba(255,255,255,0) 6%, rgba(255,255,255,0.12) 18%, rgba(255,255,255,0.34) 30%, rgba(255,255,255,0.14) 39%, rgba(255,255,255,0.02) 48%, rgba(255,255,255,0) 58%), " +
            "linear-gradient(121deg, rgba(255,255,255,0) 62%, rgba(255,255,255,0.07) 73%, rgba(255,255,255,0) 85%)"
          : // anti-reflective: NO glare — the whole point. Just a whisper so it
            // still reads as glazed.
            "linear-gradient(180deg, rgba(255,255,255,0.02) 0%, rgba(255,255,255,0.004) 100%)",
      }}
    />
  );
};

/**
 * CanvasWrap — the live canvas-edge preview for the hero (Hugo 2026-07-24: "the
 * canvas options … give you the exact way it'll look — clone it for options").
 * Built from Stephen's OWN artwork + CSS (NOT Point 101's example images):
 *   • Mirror wrap  → the image edge-to-edge with a gallery-wrap stand-off depth.
 *   • Float frame  → the canvas set inside a slim tray frame (black/white/wenge/
 *                    oak) with a fine dark shadow-gap reveal, floating off the
 *                    wall — mirroring Point 101's "Floater Frame + Stretched
 *                    Canvas". SAME footprint envelope as the framed/plain preview.
 */
const CANVAS_FLOAT_COLOR: Record<string, string> = {
  "float-black": "#17161a",
  "float-white": "#ede9e2",
  "float-wenge": "#2e211a",
  "float-oak": "#c9a368",
};
// A strong, physical stand-off shadow so the canvas reads as a chunky object
// floating off the wall (a tight contact shadow + a deep ambient drop) — plus a
// second lower ambient so the depth is unmistakable even on the dark PDP wall.
const CANVAS_DEPTH_SHADOW =
  "drop-shadow(0 3px 4px rgba(0,0,0,0.5)) drop-shadow(0 22px 30px rgba(0,0,0,0.5)) drop-shadow(0 40px 60px rgba(0,0,0,0.45))";
const CANVAS_SIZER =
  "mx-auto block max-w-full max-h-[72svh] lg:max-h-[70svh] 2xl:max-h-[72svh]";
// The mirror-wrap depth cue: the image visibly TURNS THE CORNER down the right
// edge and along the bottom (a darkened wrapped band = the stretcher thickness),
// with a soft light catch on the top-left face — so a plain print vs a
// gallery-wrapped canvas are obviously different objects (Hugo: "it doesn't show
// any change"). Point 101's stretched-canvas look, in Stephen's own artwork.
const CANVAS_WRAP_EDGE =
  "inset -16px 0 20px -12px rgba(0,0,0,0.62), " +
  "inset 0 -16px 20px -12px rgba(0,0,0,0.62), " +
  "inset 13px 13px 20px -16px rgba(255,255,255,0.24)";

// The visible stretcher-bar DEPTH of the wrapped canvas (a real gallery canvas
// is ~38mm deep). Rendered as true 3D right/bottom faces so the canvas reads as
// a solid object with thickness — Point 101's stretched-canvas look, on
// Stephen's OWN artwork (no copyrighted example images).
const CANVAS_DEPTH = "clamp(11px, 1.5vw, 24px)";
// A subtle gallery angle so the depth on the right + bottom edges is visible
// (like Point 101's canvas mockup) without reading as a gimmicky spin.
const CANVAS_TILT = "perspective(2200px) rotateX(3.2deg) rotateY(-6.5deg)";

export const CanvasWrap = ({
  active,
  edge,
  aspectRatio,
  src,
  children,
}: {
  active: boolean;
  edge: string;
  aspectRatio: number;
  /** The artwork source — used to wrap the image around the 3D side faces so
   *  the canvas visibly continues around its own depth (mirror wrap). */
  src?: string;
  children: ReactNode;
}) => {
  if (!active) return <>{children}</>;
  const floatColor = CANVAS_FLOAT_COLOR[edge];
  const artUrl = src ? asset(src) : undefined;

  // The two receding side faces (right + bottom) — the stretcher-bar thickness.
  // Mirror wrap → the artwork continues around the edge (a darkened slice of the
  // art). Float frame → the frame colour turns the corner. Both catch less light
  // than the front face, so they're shaded to read as sides in shadow.
  const rightFace = (
    <div
      aria-hidden
      className="absolute top-0 right-0 h-full"
      style={{
        width: CANVAS_DEPTH,
        transformOrigin: "right center",
        transform: "rotateY(90deg)",
        background: floatColor
          ? `linear-gradient(90deg, rgba(0,0,0,0.45), rgba(0,0,0,0.15)), ${floatColor}`
          : artUrl
            ? `linear-gradient(90deg, rgba(0,0,0,0.5), rgba(0,0,0,0.22)), url(${artUrl})`
            : "linear-gradient(90deg, rgba(0,0,0,0.5), rgba(0,0,0,0.22)), #d9d1bf",
        backgroundSize: floatColor ? undefined : "cover",
        backgroundPosition: "right center",
      }}
    />
  );
  const bottomFace = (
    <div
      aria-hidden
      className="absolute bottom-0 left-0 w-full"
      style={{
        height: CANVAS_DEPTH,
        transformOrigin: "center bottom",
        transform: "rotateX(-90deg)",
        background: floatColor
          ? `linear-gradient(180deg, rgba(0,0,0,0.15), rgba(0,0,0,0.5)), ${floatColor}`
          : artUrl
            ? `linear-gradient(180deg, rgba(0,0,0,0.22), rgba(0,0,0,0.55)), url(${artUrl})`
            : "linear-gradient(180deg, rgba(0,0,0,0.22), rgba(0,0,0,0.55)), #d9d1bf",
        backgroundSize: floatColor ? undefined : "cover",
        backgroundPosition: "center bottom",
      }}
    />
  );

  // MIRROR WRAP — a gallery-wrapped stretcher, image edge-to-edge, standing off
  // the wall with a visible ~38mm depth (true 3D side faces + a subtle tilt).
  if (!floatColor) {
    return (
      <div className={CANVAS_SIZER} style={{ aspectRatio: String(aspectRatio || 1) }}>
        <div
          className="relative w-full h-full"
          style={{
            transformStyle: "preserve-3d",
            transform: CANVAS_TILT,
            filter: CANVAS_DEPTH_SHADOW,
          }}
        >
          {rightFace}
          {bottomFace}
          <div
            className="relative w-full h-full overflow-hidden"
            style={{
              transform: `translateZ(${CANVAS_DEPTH})`,
              // A faint light catch on the top-left front face — the canvas edge
              // catching gallery light — so the front reads as a lit surface.
              boxShadow: CANVAS_WRAP_EDGE,
            }}
          >
            {children}
          </div>
        </div>
      </div>
    );
  }

  // FLOAT FRAME — the canvas set inside a slim tray frame with a shadow-gap
  // reveal, the whole piece carrying the same real 3D depth + gallery tilt.
  const tray = "clamp(9px, 1.7vw, 26px)";
  const gap = "clamp(4px, 0.6vw, 9px)";
  return (
    <div className={CANVAS_SIZER} style={{ aspectRatio: String(aspectRatio || 1) }}>
      <div
        className="relative w-full h-full"
        style={{
          transformStyle: "preserve-3d",
          transform: CANVAS_TILT,
          filter: CANVAS_DEPTH_SHADOW,
        }}
      >
        {rightFace}
        {bottomFace}
        <div
          className="w-full h-full"
          style={{
            boxSizing: "border-box",
            background: floatColor,
            padding: tray,
            transform: `translateZ(${CANVAS_DEPTH})`,
            borderRadius: "1px",
          }}
        >
          {/* the dark shadow-gap reveal between the tray frame and the canvas */}
          <div className="w-full h-full" style={{ background: "#0a0908", padding: gap }}>
            <div
              className="relative w-full h-full overflow-hidden"
              style={{ boxShadow: "0 1px 5px rgba(0,0,0,0.6)" }}
            >
              {children}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const FrameWrap = ({
  active,
  frameStyle,
  glazing,
  aspectRatio,
  children,
}: {
  active: boolean;
  frameStyle: string;
  glazing: string;
  aspectRatio: number;
  children: ReactNode;
}) => {
  if (!active) return <>{children}</>;

  const sizerClass =
    "mx-auto block max-w-full max-h-[72svh] lg:max-h-[70svh] 2xl:max-h-[72svh]";

  const src = asset(FRAME_ASSET[frameStyle] ?? FRAME_ASSET["natural-oak"]);
  // The moulding width. A real gallery moulding is a slim, confident band — kept
  // in the same footprint envelope the flat border used so the size invariant
  // holds. clamp() so it stays proportionate from phone to 4K.
  const moulding = "clamp(17px, 2.9vw, 46px)";

  return (
    <div
      className={sizerClass}
      style={{
        aspectRatio: String(aspectRatio || 1),
        boxSizing: "border-box",
        borderStyle: "solid",
        borderWidth: moulding,
        // Tailwind Preflight paints a gray-200 border under everything; without
        // this it bleeds through the border-image's anti-aliased mitre corners as
        // faint light ticks. Transparent underlay → only the moulding shows.
        borderColor: "transparent",
        borderImageSource: `url(${src})`,
        borderImageSlice: `${FRAME_SLICE}`,
        borderImageWidth: moulding,
        borderImageRepeat: "stretch",
        // Cast shadow — the framed piece floats off the wall: a tight contact
        // shadow + a soft ambient drop. (Invisible on a pure-black wall, present
        // on light walls / the PDP's tinted wall.)
        filter:
          "drop-shadow(0 2px 3px rgba(0,0,0,0.45)) drop-shadow(0 26px 44px rgba(0,0,0,0.5))",
        borderRadius: "1px",
      }}
    >
      {/* The print, set into the frame's rebate (no mat). `relative` +
          `overflow-hidden` make it the positioning context for the absolutely-
          filled print + glazing, so the print's intrinsic size can't push the
          box past its aspect-ratio. A soft inner shadow recesses the sheet under
          the moulding lip. */}
      <div
        className="relative w-full h-full overflow-hidden"
        style={{
          boxShadow:
            "inset 0 2px 7px rgba(0,0,0,0.5), inset 0 0 0 1px rgba(0,0,0,0.45)",
        }}
      >
        {children}
        <GlazingOverlay glazing={glazing} />
      </div>
    </div>
  );
};
