// colourway-tints.mjs — build-time colour extraction for the PDP "Painted
// Wall, Lit" atmosphere (2026-07-03 design panel; replaces the runtime blurred
// AmbientBackdrop blob).
//
// For every colourway image referenced in src/data/paintings.ts:
//   downsample 24×24 via ImageMagick → sRGB→OKLCH per pixel → chroma-weighted
//   median hue H over pixels with C > 0.04 (fallback warm umber H=55 when
//   <5% qualify) → two RE-LIT colours at house lightness/chroma:
//     wall = oklch(0.32 0.055 H)   halo = oklch(0.62 0.09 H)
//   resolved to sRGB hex at build time.
//
// Outputs:
//   src/lib/colourwayTints.ts        (auto-generated, committed)
//   <scratch>/tint-contact-sheet.html (eyeball pass artifact)
//
// Zero new deps: shells out to `magick`, colour math inline. Re-run whenever a
// colourway image changes. OVERRIDES at the bottom of the generated file win.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(new URL(".", import.meta.url).pathname, "..");
const paintings = fs.readFileSync(path.join(ROOT, "src/data/paintings.ts"), "utf8");
const images = [...new Set([...paintings.matchAll(/image:\s*"(\/img\/paintings\/[^"]+)"/g)].map(m => m[1]))];

// ---- sRGB -> OKLab/OKLCH (Björn Ottosson's reference implementation) ----
const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const linearToSrgb = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
function rgbToOklch(r8, g8, b8) {
  const r = srgbToLinear(r8 / 255), g = srgbToLinear(g8 / 255), b = srgbToLinear(b8 / 255);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const bb = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return { L, C: Math.hypot(a, bb), H: (Math.atan2(bb, a) * 180) / Math.PI };
}
function oklchToHex(L, C, Hdeg) {
  const h = (Hdeg * Math.PI) / 180;
  const a = C * Math.cos(h), bb = C * Math.sin(h);
  const l = (L + 0.3963377774 * a + 0.2158037573 * bb) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * bb) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * bb) ** 3;
  let r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  let g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  let b = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  const to8 = (c) => Math.max(0, Math.min(255, Math.round(linearToSrgb(Math.max(0, Math.min(1, c))) * 255)));
  return "#" + [to8(r), to8(g), to8(b)].map((v) => v.toString(16).padStart(2, "0")).join("");
}

const rows = [];
for (const img of images) {
  const file = path.join(ROOT, "public", img);
  if (!fs.existsSync(file)) { console.warn("MISSING", img); continue; }
  const txt = execFileSync("magick", [file, "-resize", "24x24!", "-depth", "8", "txt:-"], { encoding: "utf8" });
  const px = [...txt.matchAll(/srgba?\((\d+)[,%]?\s*,?(\d+)[,%]?\s*,?(\d+)/g)].map(m => rgbToOklch(+m[1], +m[2], +m[3]));
  const chromatic = px.filter(p => p.C > 0.04);
  let H;
  if (chromatic.length < px.length * 0.05) {
    H = 55; // warm umber fallback for near-mono canvases
  } else {
    // chroma-weighted circular median: pick the hue minimising weighted
    // circular distance (robust to bimodal palettes, unlike a mean).
    let best = { h: 55, cost: Infinity };
    for (let cand = 0; cand < 360; cand += 3) {
      let cost = 0;
      for (const p of chromatic) {
        let d = Math.abs((((p.H - cand) % 360) + 540) % 360 - 180);
        cost += d * p.C;
      }
      if (cost < best.cost) best = { h: cand, cost };
    }
    H = best.h;
  }
  rows.push({ img, H: Math.round(H), wall: oklchToHex(0.32, 0.055, H), halo: oklchToHex(0.62, 0.09, H) });
  console.log(img.split("/").pop(), "H=" + Math.round(H), rows.at(-1).wall, rows.at(-1).halo);
}

// Carry forward any hand-written OVERRIDES from the existing generated file
// so a re-run never wipes an eyeballed fix.
let overridesBlock = "const OVERRIDES: Record<string, ColourwayTint> = {};";
const existingPath = path.join(ROOT, "src/lib/colourwayTints.ts");
if (fs.existsSync(existingPath)) {
  const m = fs.readFileSync(existingPath, "utf8").match(/const OVERRIDES[\s\S]*?^};/m);
  if (m) overridesBlock = m[0];
}

const ts = `// AUTO-GENERATED by scripts/colourway-tints.mjs — do not edit by hand
// (EXCEPT the OVERRIDES map, which re-runs preserve).
// Per-colourway "Painted Wall" atmosphere tints: hue extracted from the
// artwork (chroma-weighted OKLCH median), lightness/chroma are HOUSE values
// (wall oklch(0.32 0.055 H), halo oklch(0.62 0.09 H)) so every page shares
// one material register while the hue follows the selected colourway.
// Re-run the script when a colourway image changes. OVERRIDES win.

export interface ColourwayTint {
  wall: string;
  halo: string;
}

const GENERATED: Record<string, ColourwayTint> = {
${rows.map(r => `  "${r.img}": { wall: "${r.wall}", halo: "${r.halo}" }, // H ${r.H}`).join("\n")}
};

/** Hand-fix a colourway here if the extracted hue ever reads wrong. */
${overridesBlock}

export const DEFAULT_TINT: ColourwayTint = { wall: "#2a241c", halo: "#8a7a63" };

export const COLOURWAY_TINTS: Record<string, ColourwayTint> = {
  ...GENERATED,
  ...OVERRIDES,
};
`;
fs.writeFileSync(path.join(ROOT, "src/lib/colourwayTints.ts"), ts);

const sheet = `<!doctype html><meta charset="utf8"><body style="background:#0a0908;color:#ede6d6;font-family:sans-serif;display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:12px;padding:16px">
${rows.map(r => `<div style="border:1px solid #333;padding:10px;background:linear-gradient(to bottom, ${r.wall}85, ${r.wall}42 44%, transparent)">
  <img src="../public${r.img}" style="width:120px;height:120px;object-fit:cover;float:left;margin-right:10px">
  <b>${r.img.split("/").pop()}</b><br>H ${r.H}<br>
  <span style="display:inline-block;width:44px;height:24px;background:${r.wall}"></span> wall ${r.wall}<br>
  <span style="display:inline-block;width:44px;height:24px;background:${r.halo}"></span> halo ${r.halo}
</div>`).join("\n")}
</body>`;
fs.writeFileSync(path.join(ROOT, "docs/tint-contact-sheet.html"), sheet);
console.log(`\nwrote src/lib/colourwayTints.ts (${rows.length} colourways) + docs/tint-contact-sheet.html`);
